### ISSUE TITLE
외부 API 구현

### ISSUE THREAD

**Issue by So-chiru** [loveliveall/loveliveall.github.io#8]
외부에서도 API로 일정을 가져오는 기능이 있으면 참 좋을 것 같습니다

![TranscodedWallpaper](https://user-images.githubusercontent.com/32066651/59491628-1a722a80-8ec2-11e9-9509-1c181c6b99c7.jpg)
![요우우우우](https://user-images.githubusercontent.com/32066651/59491629-1a722a80-8ec2-11e9-888d-31c95a7087a0.png)
![1555126067](https://user-images.githubusercontent.com/32066651/59491630-1b0ac100-8ec2-11e9-9448-3f87467d5457.jpg)

짤은 조공하고 갑니다 ^^

**Comment by loveliveall** [comment]
API 구현은 완료했고 현재 서버 올라가 있는 상태입니다. 명세서 작성 중이니 완료되는 대로 다시 이 이슈에 코멘트 달고 닫도록 하겠습니다

**Comment by loveliveall** [comment]
위키에 명세 작성해 두었습니다: [API Documentation](https://github.com/loveliveall/loveliveall.github.io/wiki/API-Documentation)

일단 이슈 닫아둘테니 뭔가 추가 요청이나 이런게 있는 경우 열고 다시 작성해주시면 돼영

다시 작성해주실때 제쪽에 멘션 걸어서 알림 오게 해주시면 감사...
